services:
  et-cassandra-1:
    container_name: et-cassandra-1
    image: cassandra:4.1.2
    volumes:
      - "et-cassandra-1-vol:/var/lib/cassandra"
    environment:
      CASSANDRA_SEEDS: et-cassandra-1,et-cassandra-2,et-cassandra-3
      HEAP_NEWSIZE: 400M
      MAX_HEAP_SIZE: 2G
      CASSANDRA_CLUSTER_NAME: et-cassandra
      CASSANDRA_AUTHENTICATOR: PasswordAuthenticator
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD_SEEDER: yes
      CASSANDRA_PASSWORD: cassandra
    networks:
      - et-network
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra", "-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10

  et-cassandra-2:
    container_name: et-cassandra-2
    image: cassandra:4.1.2
    volumes:
      - "et-cassandra-2-vol:/var/lib/cassandra"
    environment:
      CASSANDRA_SEEDS: et-cassandra-1,et-cassandra-2,et-cassandra-3
      HEAP_NEWSIZE: 400M
      MAX_HEAP_SIZE: 2G
      CASSANDRA_CLUSTER_NAME: et-cassandra
      CASSANDRA_AUTHENTICATOR: PasswordAuthenticator
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
    networks:
      - et-network
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra", "-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10

  et-cassandra-3:
    container_name: et-cassandra-3
    image: cassandra:4.1.2
    volumes:
      - "et-cassandra-3-vol:/var/lib/cassandra"
    environment:
      CASSANDRA_SEEDS: et-cassandra-1,et-cassandra-2,et-cassandra-3
      HEAP_NEWSIZE: 400M
      MAX_HEAP_SIZE: 2G
      CASSANDRA_CLUSTER_NAME: et-cassandra
      CASSANDRA_AUTHENTICATOR: PasswordAuthenticator
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
    networks:
      - et-network
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra", "-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10

  et-cassandra-init:
    container_name: et-cassandra-init
    image: cassandra:4.1.2
    depends_on:
      et-cassandra-1:
        condition: service_healthy
      et-cassandra-2:
        condition: service_healthy
      et-cassandra-3:
        condition: service_healthy
    networks:
      - et-network
    volumes:
      - ./schema.cql:/schema.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh et-cassandra-1 -f /schema.cql"

volumes:
  et-cassandra-1-vol:
  et-cassandra-2-vol:
  et-cassandra-3-vol:

networks:
  # create network externally: `docker network create et-network`
  et-network:
    external: true