services:
  et-mongodb:
    container_name: et-mongodb
    image: mongo:5.0.28
    ports:
      - 27017:27017
    volumes:
      - "et-mongodb-vol:/data"
    networks:
      - et-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: et

volumes:
  et-mongodb-vol:

networks:
  # create network externally: `docker network create et-network`
  et-network:
    external: true