apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-deployment
  labels:
    easytrack: grpc
spec:
  replicas: 2
  selector:
    matchLabels:
      easytrack: grpc
  template:
    metadata:
      labels:
        easytrack: grpc
    spec:
      containers:
        - image: qobiljon/et-grpc-server:1.0
          name: et-grpc-server
          ports:
            - containerPort: 50051